version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: bank-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20

  customers-service:
    build: ./customers-service
    container_name: customers-service
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      # apunta al mysql del compose (host = mysql)
      SPRING_R2DBC_URL: r2dbc:mysql://mysql:3306/bank_customers
      SPRING_R2DBC_USERNAME: root
      SPRING_R2DBC_PASSWORD: root
      SPRING_FLYWAY_URL: jdbc:mysql://mysql:3306/bank_customers?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_FLYWAY_USER: root
      SPRING_FLYWAY_PASSWORD: root

  accounts-service:
    build: ./accounts-service
    container_name: accounts-service
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_R2DBC_URL: r2dbc:mysql://mysql:3306/bank_accounts
      SPRING_R2DBC_USERNAME: root
      SPRING_R2DBC_PASSWORD: root
      SPRING_FLYWAY_URL: jdbc:mysql://mysql:3306/bank_accounts?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_FLYWAY_USER: root
      SPRING_FLYWAY_PASSWORD: root

volumes:
  mysql_data: